# Generated by Django 4.1.2 on 2022-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(blank=True, default=1, null=True)),
                ('sessionID', models.IntegerField(blank=True, default=1, null=True)),
                ('searchID', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
