# Generated by Django 4.1.2 on 2022-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('sessionID', models.IntegerField(blank=True, null=True)),
                ('sessionName', models.CharField(max_length=30)),
                ('sessionDescription', models.TextField(max_length=250)),
                ('sessionPassword', models.CharField(max_length=30)),
                ('searchID', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('startsAt', models.DateTimeField(auto_now=True)),
                ('endsAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
