# Generated by Django 4.1.2 on 2022-10-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=30)),
                ('username', models.TextField(max_length=15)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
    ]
