# Generated by Django 4.1.2 on 2022-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='endsAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='startsAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
