# Generated by Django 4.1.2 on 2022-12-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessionmodel_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.IntegerField(null=True)),
                ('presentation', models.IntegerField(null=True)),
                ('delivery', models.IntegerField(null=True)),
                ('innovativeness', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sessionmodel',
            options={'verbose_name': 'Session Name', 'verbose_name_plural': 'Session Rooms'},
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='endsAt',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='userID',
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='sessionID',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='startsAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
