# Generated by Django 4.1.2 on 2022-11-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='searchID',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.IntegerField(null=True)),
                ('presentation', models.IntegerField(null=True)),
                ('delivery', models.IntegerField(null=True)),
                ('innovativeness', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=500)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
    ]
