# Generated by Django 4.1.2 on 2022-12-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ratingmodel_alter_sessionmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='sessionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel'),
        ),
        migrations.CreateModel(
            name='AverageRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AveragePunctuality', models.IntegerField(null=True)),
                ('AveragePresentation', models.IntegerField(null=True)),
                ('AverageDelivery', models.IntegerField(null=True)),
                ('AverageInnovativeness', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=500)),
                ('sessionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
        ),
    ]
