# Generated by Django 4.1.2 on 2022-11-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sessionmodel_searchid_ratingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='userID',
        ),
    ]
