# Generated by Django 4.1.2 on 2022-12-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ratingmodel_sessionid_averageratingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averageratingmodel',
            name='feedback',
        ),
    ]
