# Generated by Django 4.1.2 on 2022-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_averageratingmodel_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageratingmodel',
            name='AverageDelivery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='averageratingmodel',
            name='AverageInnovativeness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='averageratingmodel',
            name='AveragePresentation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='averageratingmodel',
            name='AveragePunctuality',
            field=models.FloatField(null=True),
        ),
    ]
