# Generated by Django 4.1.2 on 2022-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ratingmodel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='sessionPassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
