# Generated by Django 4.1.2 on 2022-12-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sessionmodel_sessionpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='sessionID',
        ),
    ]
