# Generated by Django 4.1.2 on 2022-12-14 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionmodel_ratingopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='ratingOpen',
            field=models.IntegerField(choices=[(1, 'Open'), (0, 'Close')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Live'), (3, 'Ended')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
        ),
    ]
